config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users do
    resources :pictures
  end
  resources :posts
  resources :categories
  resources :searches
  get 'tags/:tag', to: 'pictures#index', as: :tag
  root "posts#index"
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :title, :image, presence: true
  belongs_to :user
  belongs_to :category
  mount_uploader :image, ImageUploader
  acts_as_taggable
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :find_picture, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tag]
      @pictures = Picture.tagged_with(params[:tag])
    else
      @pictures = current_user.pictures
    end
    @categories = Category.all
    @tags = Picture.all.tag_counts
    # @pictures = Picture.all
    # @categories = Category.all
    # @tags = Picture.all.tag_counts
  end

  def new
    @picture = current_user.pictures.build
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    if @picture.save
      redirect_to user_pictures_path, notice: "Sucsessfully created new Post"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @picture.update(picture_params)
      redirect_to user_pictures_path, notice: "Picture was Succsessfully updates!"
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to user_pictures_path
  end

  private

  def find_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title, :image, :category_id, :tag_list)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_filter.html.haml
.col-lg-3
	.well.sidebar-nav
		%h3 Sidebar
		%ul.nav.nav-list
			%li Tags
			= select_tag 'tags', options_for_select(@tags.collect{ |u| [u.name, u.id] }), multiple: true
			%li Categories

app/views/pictures/_form.html.haml
= simple_form_for [:user, @picture],html: {multipart: true} do |f|
	- if @picture.errors.any?
		#errors
			%h2
			= pluralize(@picture.errors.count, 'error')
			prevented this picture from saving
			%ul
				- @picture.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.file_field :image
	.form-group
		= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, input_html: { class: 'form-control' }
	.form-group
		= f.input :tag_list
	
	= f.button :submit, class: "btn btn-primary"

app/views/pictures/_picture.html.haml
-# .picture	
-# 	.col-lg-9
-# 		%p
-# 		= link_to "Add a Picture", new_user_picture_url(current_user)
-# 		= link_to "Advanced Search", new_search_path
-# 		.picture
-# 			%h1
-# 				= link_to picture.title, user_picture_url(current_user, picture) 
-# 			%p
-# 			Caregory:
-# 			= link_to picture.category.name, picture.category
-# 			%p
-# 			= image_tag picture.image_url(:thumb) if picture.image?
-# 			%p 
-# 				Tags: #{ raw picture.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') }
-# 			.actions
-# 				= link_to "edit", edit_user_picture_path(current_user, picture)
-# 				= link_to "remove", user_picture_url(current_user, picture) , data: { confirm: 'Are you sure?' }, :method => :	delete

-# .picture
-# 	%h2= link_to picture.title
-# 	.details
-# 	- if product.category
-# 	| Category: #{picture.category.name}

.product
	%h2= link_to picture.title
	.details
		- if picture.category
			| Category: #{picture.category.name}

app/views/pictures/edit.html.haml
.col-md-6.col-md-offset-3		
	%h1 Edit Picture

	= render 'form'

	=link_to 'Cancel', user_pictures_path

app/views/pictures/index.html.haml
.col-lg-9
	%p
	= link_to "Add a Picture", new_user_picture_url(current_user)
	= link_to "Advanced Search", new_search_path

	- @pictures.each do |picture|
		.picture
			%h1
				= link_to picture.title, user_picture_url(current_user, picture) 
			%p
			Caregory:
			=  picture.category.name if picture.category.present?
			%p
			= image_tag picture.image_url(:thumb) if picture.image?
			%p 
				Tags: #{ raw picture.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') }
			.actions
				= link_to "edit", edit_user_picture_path(current_user, picture)
				= link_to "remove", user_picture_url(current_user, picture) , data: { confirm: 'Are you sure?' }, :method => :delete

	-# %ol.carousel-indicators

	-# 	- current_user.pictures.each_with_index do |photo, n|
	-# 		%li.if.n{:class => "\#{'active' == 0}", "data-slide-to" => "\#{n}", "data-target" => "#MyCarousel"}
	-# .carousel-inner{:role => "listbox"}
	-# 	.item.active
	-# 		= image_tag current_user.pictures.first.image_url
	-# 	- current_user.pictures.drop(1).each do |photo|
	-# 		.item
	-# 			= image_tag photo.image_url
	-# - arr = []
	-# 	- current_user.pictures.each do |pic|
	-# 	- arr<<pic.image_url
	-# = carousel_for(arr)

app/views/pictures/new.html.haml
.col-md-6.col-md-offset-3	
	%h1  New Picture

	= render 'form'

	=link_to 'Back', user_pictures_url(current_user)

app/views/pictures/show.html.haml
%h1= @picture.title
%p
Submited by
= @picture.user.nickname

%br/
= link_to 'Back', user_pictures_url
= link_to 'Edit', edit_user_picture_path
= link_to 'Delete', user_picture_url, method: :delete, data: { confirm: 'Are you sure?' }