config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users do
    resources :pictures
  end
  resources :posts
  resources :categories
  resources :searches
  get 'tags/:tag', to: 'pictures#index', as: :tag
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  scope :published, -> { where(published: true) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  
  def index

  	@posts = Post.published.order('created_at')

  end

  def show

  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: "Sucsessfully created new Post"
    else
      render 'new'
    end
  end

  def update
  	if @post.update(post_params)
  		redirect_to @post, notice: "Slideshow was Succsessfully updates!"
  	else
  		render 'edit'
  	end
  end

  def edit
  	
  end

  def destroy
  	@post.destroy
  	redirect_to root_path	
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :published)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for @post, html: {multipart: true} do |f|
	- if @post.errors.any?
		#errors
			%h2
			= pluralize(@post.errors.count, 'error')
			prevented this Post from saving
			%ul
				- @post.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	.form_group
		= f.label  'Public'
		= f.radio_button :published, true, :value => true
		= f.label  'Private'
		= f.radio_button :published, false, :value => false

	
	= f.button :submit, class: "btn btn-primary"

app/views/posts/edit.html.haml
.col-md-6.col-md-offset-3		
	%h1 Edit Slideshow

	= render 'form'

	=link_to 'Cancel', @post

app/views/posts/index.html.haml
- @posts.each do |post|
	- if post.published
		%h2= link_to post.title, post

app/views/posts/new.html.haml
.col-md-6.col-md-offset-3	
	%h1  New Form

	= render 'form'

	=link_to 'Back', root_path

app/views/posts/show.html.haml
%h1= @post.title
%p= @post.description
%p
Submited by
= @post.user.nickname

%br/
= link_to 'Back', root_path
= link_to 'Edit', edit_post_path
= link_to 'Delete', post_path, method: :delete, data: { confirm: 'Are you sure?' }