config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users do
    resources :pictures
  end
  resources :posts
  resources :categories
  resources :searches
  get 'tags/:tag', to: 'pictures#index', as: :tag
  root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_many :pictures
  has_ancestry
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, success: 'New Category created!'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Category not created'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to categories_path, success: 'Category updated!'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, success: 'Category deleted!'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for @category, html: {multipart: true} do |f|
	- if @category.errors.any?
		#errors
			%h2
			= pluralize(@category.errors.count, 'error')
			prevented this category from saving
			%ul
				- @category.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :name, input_html: { class: 'form-control' }
	.form-group
		= f.label :parent_id
		%p
			= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, input_html: { class: 'form-control' }
	
	= f.button :submit, class: "btn btn-primary"

app/views/categories/edit.html.haml
.col-md-6.col-md-offset-3		
	%h1 Edit Category

	= render 'form'

	=link_to 'Cancel', categories_path

app/views/categories/index.html.haml
%h1= t('.title')
.buttons_panel
  = link_to 'New Category', new_category_path, class: 'btn btn-outline-primary btn-sm'
%section#categories
  %table.table
    %thead
      %tr
        %th #
        %th Name
        %th Parent category
        %th
    %tbody
      - @categories.each_with_index do |category, index|
        %tr
          %td= index + 1
          %td= category.name
          %td= category.parent.name if category.parent.present?
          %td
            = link_to 'Edit', edit_category_path(category), class: 'btn btn-outline-primary btn-sm'
            = link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'

app/views/categories/new.html.haml
.col-md-6.col-md-offset-3	
	%h1  New Category

	= render 'form'

	=link_to 'Back', categories_path

app/views/categories/show.html.haml
%h1= @categories.name
%p


%br/
= link_to 'Back', catgories_path
= link_to 'Edit', edit_category_path
= link_to 'Delete', categories_path, method: :delete, data: { confirm: 'Are you sure?' }